[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.21"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
remappings = [
    "@solmate/=lib/boring-vault/lib/solmate/src/",
    "@boring-vault/=lib/boring-vault/src/",
    "@forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/boring-vault/lib/openzeppelin-contracts/",
    "@src/=src/",
]
